### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by jaboge** [ngrok/terraform-provider-ngrok#7]
Hi,

Terraform gives me the following error message upon applying the below code:

> ngrok_reserved_domain.my-test-domain: Creating...
> ╷
> │ Error: Provider produced inconsistent result after apply
> │ 
> │ When applying changes to ngrok_reserved_domain.my-test-domain, provider "provider[\"registry.terraform.io/ngrok/ngrok\"]" produced an unexpected new value: Root resource was present, but now absent.
> │ 
> │ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```
terraform {
  required_providers {
    ngrok = {
      source = "ngrok/ngrok"
      version = "0.0.25"
    }
  }
}

variable "ngrok-api-key" {
  type = string
}

provider "ngrok" {
  api_key = var.ngrok-api-key
}

resource "ngrok_reserved_domain" "my-test-domain" {
  name   = "asdfjkl3jsj"
  region = "eu"
  certificate_management_policy {
    authority        = "letsencrypt"
    private_key_type = "ecdsa"
  }
}
```

**Comment by dje** [comment]
Hi @jaboge,

We've recently released a new version of this Terraform provider that should improve error reporting and debugging. Would you mind retrying with the current release? Thank you!

**Comment by jaboge** [comment]
Hi @dje

Version 0.0.27 works as intended!

FYI: I did have to remove the certificate_management_policy block, which I have come to understand is redundant when using the ngrok.io wildcard certificate.

Thanks!

**Comment by dje** [comment]
Good to hear! Thanks again.
